### ISSUE TITLE
Can not build in project with 0.12.1

### ISSUE THREAD

**Issue by cdmikechen** [apache-superset/superset-ui#265]
I clone project and run yarn install successfully, but yarn build failed.
```sh
yarn run v1.21.0
$ yarn run build:cjs && yarn run build:esm && yarn run type:dts && yarn run build:assets
$ NODE_ENV=production beemo babel --extensions=".js,.jsx,.ts,.tsx" ./src --out-dir lib/ --delete-dir-on-start --minify --workspaces="@superset-ui/!(demo|generator-superset)"
[1/2] CONFIG Creating config files
[2/2] DRIVER Running Babel v7.6.4 driver

Successfully compiled 17 files with Babel.
Successfully compiled 14 files with Babel.
Successfully compiled 10 files with Babel.
Successfully compiled 11 files with Babel.
Successfully compiled 4 files with Babel.
Successfully compiled 10 files with Babel.
Successfully compiled 17 files with Babel.
Successfully compiled 22 files with Babel.
Successfully compiled 20 files with Babel.
Successfully compiled 5 files with Babel.
Successfully compiled 18 files with Babel.

🤖  Powered by Beemo v1.1.1
$ NODE_ENV=production beemo babel --extensions=".js,.jsx,.ts,.tsx" ./src --out-dir esm/ --delete-dir-on-start --esm --minify --workspaces="@superset-ui/!(demo|generator-superset)"
[1/2] CONFIG Creating config files
[2/2] DRIVER Running Babel v7.6.4 driver

Successfully compiled 17 files with Babel.
Successfully compiled 14 files with Babel.
Successfully compiled 10 files with Babel.
Successfully compiled 11 files with Babel.
Successfully compiled 4 files with Babel.
Successfully compiled 10 files with Babel.
Successfully compiled 17 files with Babel.
Successfully compiled 22 files with Babel.
Successfully compiled 20 files with Babel.
Successfully compiled 5 files with Babel.
Successfully compiled 18 files with Babel.

🤖  Powered by Beemo v1.1.1
$ NODE_ENV=production beemo typescript --workspaces="@superset-ui/!(demo|generator-superset)" --emitDeclarationOnly
[1/2] CONFIG Creating config files (failed)

The "to" argument must be of type string. Received type object
TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at Object.relative (path.js:1163:5)
    at context.workspaces.forEach.wsPath (/Volumes/Transcend/Apache/superset-ui/node_modules/@superset-ui/build-config/configs/typescript.js:24:33)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Volumes/Transcend/Apache/superset-ui/node_modules/@superset-ui/build-config/configs/typescript.js:23:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Can anybody help me to check the cause？
my env version is :
node.js version: v10.16.0
npm version: 6.9.0
typescript version: 3.7.3
I have merged https://github.com/apache-superset/superset-ui/pull/227

**Comment by domoritz** [comment]
Looks like the issue is in the beemo config (https://github.com/beemojs/beemo/issues/74). Is there a timeline for a fixed release?

@kristw This is preventing updates for react-vega.

**Comment by cdmikechen** [comment]
glad to see that. I will check this PR later

**Comment by kristw** [comment]
@domoritz @cdmikechen  I am working on it. Ran into more issues than expected so this may take a while. 
https://github.com/apache-superset/superset-ui/pull/281

The sad side of coming back from long vacation... everything breaks!

**Comment by domoritz** [comment]
Thank you @kristw. I feel you.
