### ISSUE TITLE
Not able to build 

### ISSUE THREAD

**Issue by tsuki42** [apache-superset/superset-ui#325]
The `yarn build` command is failing and I don't know why.
Here is the snippet of the error log.
```
superset/superset-ui# yarn build
yarn run v1.22.4
$ yarn babel && yarn type && yarn build:assets
$ yarn babel:cjs && yarn babel:esm
$ nimbus babel --clean --workspaces="@superset-ui/!(demo|generator-superset)"
[1/2] CONFIG Creating config files
[2/2] DRIVER Running Babel v7.8.3 driver (failed)

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /root/superset/superset-ui/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:524:9)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:661:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:963:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/root/superset/superset-ui/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```
node version used: v13.12.0
yarn version used: 1.22.4

**Comment by kristw** [comment]
`master` seems to be working. When did you last pull?
